jobs:
  -
    job: 'core_build'

    # dependsOn: 'iac_build'

    variables:
      directory: 'olt-dotnetcore'
      solution: 'OLT.Libraries.sln'
      buildConfiguration: Release

    pool:
      # vmImage: 'windows-latest'
      vmImage: 'ubuntu-latest'

    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          echo Package Version = '$(packageVersion)'
          echo Package Version = '$(Build.SourcesDirectory)'


    - task: DotNetCoreCLI@2
      displayName: 'Resore Nuget'
      inputs:
        command: 'restore'
        projects: '$(directory)/$(solution)'
        feedsToUse: 'select'
        vstsFeed: 'olt-packages'


    - task: DotNetCoreCLI@2
      displayName: 'Running Test'
      inputs:
        command: 'test'
        projects: '$(directory)/$(solution)'
        testRunTitle: 'Core Unit Test'
        arguments: '--configuration $(BuildConfiguration) --collect:"XPlat Code Coverage"'

    - task: PublishCodeCoverageResults@1
      displayName: 'Publish Test Coverage Results [$(Agent.TempDirectory)]'
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(Agent.TempDirectory)/**/*coverage.cobertura.xml'
        # reportDirectory: '$(Agent.TempDirectory)/CodeCoverage/'

    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: 'build'
        projects: '$(directory)/$(solution)'
        arguments: '--configuration $(BuildConfiguration)'
        versioningScheme: byEnvVar
        versionEnvVar: 'packageVersion'
        # versionEnvVar: 'GitVersion.SemVer'
        
    - task: CopyFiles@2
      displayName: 'Copy $(Build.SourcesDirectory) to: $(Build.ArtifactStagingDirectory)'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: '**/*.nupkg'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        flattenFolders: true


    - publish: $(Build.ArtifactStagingDirectory)
      displayName: 'Publish Package Artifact'
      artifact: 'olt-dotnetcore'